services:
  - type: web
    runtime: node
    name: sv-marker-backend
    region: singapore
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: cd apps/backend && npm start
    envVars:
      - key: WEB_ORIGIN
        value: https://utlis.github.io
      - key: STANZA_SERVER_ORIGIN
        value: https://sv-marker-stanza-server.onrender.com
      - key: GEMINI_API_KEY
        sync: false
