export {
  sentenceElementNameOptions,
  allowedSentenceElementNameOptions,
  SentenceStructureDocumentSchema,
  type Word,
  type SentenceElementName,
  type SentenceConstituentType,
  type SentenceStructureElement,
  type Modification,
  type CoordinationPartType,
  type CoordinationPart,
  type Coordination,
  type Sentence,
  type SentenceStructureDocument,
} from "./schema.js";
export {
  SimplifiedSentenceStructureDocumentSchema,
  type SimplifiedSentenceStructureDocument,
} from "./codecs/simplified-codec.js";
export {
  createSentenceStructureDocumentFromText,
  createSentenceStructureDocumentFromWords,
  createSentenceStructureDocumentFromSimplifiedSentenceStructureDocument,
  createSentenceStructureDocumentFromJSONString,
  createSentenceStructureDocumentFromXMLString,
  sentenceStructureDocumentToText,
  sentenceStructureDocumentToSimplifiedSentenceStructureDocument,
  sentenceStructureDocumentToJSONString,
  sentenceStructureDocumentToXMLString,
  sentenceStructureDocumentToSentenceStructureDocumentForest,
  sentenceStructureDocumentToSentenceStructureDecoratedDocumentForest,
  updateSentenceStructureDocumentText,
  clearSentenceStructureAnnotations,
  addSentenceStructureElement,
  updateSentenceElementName,
  deleteSentenceStructureElement,
  addModification,
  deleteModification,
  addCoordination,
  deleteCoordination,
} from "./operations.js";
export type {
  SentenceStructureDocumentWordNode,
  SentenceStructureDocumentSentenceStructureElementNode,
  SentenceStructureDocumentCoordinationPartNode,
  SentenceStructureDocumentCoordinationNode,
  SentenceStructureDocumentRootNode,
  SentenceStructureDocumentSentenceTree,
  SentenceStructureDocumentForest,
  SentenceStructureDocumentNode,
} from "./tree/types.js";
export type {
  SentenceStructureDecoratedDocumentWordNode,
  SentenceStructureDecoratedDocumentSentenceStructureElementNode,
  SentenceStructureDecoratedDocumentCoordinationPartNode,
  SentenceStructureDecoratedDocumentCoordinationNode,
  SentenceStructureDecoratedDocumentRootNode,
  SentenceStructureDecoratedDocumentSentenceTree,
  SentenceStructureDecoratedDocumentForest,
  SentenceStructureDecoratedDocumentNode,
} from "./tree/decorated/types.js";
