export {
  sentenceElementNameOptions,
  sentenceElementRangeTypeOptions,
  sentenceElementRangeTypeToAllowedSentenceElementNameOptionsMap,
  sentenceStructureRangeTypeOptions,
  sentenceStructureRangeTypeToAllowedSentenceElementNameOptionsMap,
  coordinationChildTypeOptions,
  SentenceStructureDataSchema,
  type Word,
  type SentenceElementName,
  type SentenceElementRangeType,
  type SentenceStructureRangeType,
  type RangeType,
  type Range,
  type Relation,
  type CoordinationChildType,
  type CoordinationChild,
  type Coordination,
  type SentenceStructureData,
} from "./schema.js";
export {
  SimplifiedAnnotationDataSchema,
  SimplifiedSentenceStructureDataSchema,
  type SimplifiedAnnotationData,
  type SimplifiedSentenceStructureData,
} from "./simplified-schema.js";
export {
  createSentenceStructureDataFromText,
  createSentenceStructureDataFromStringData,
  createSentenceStructureDataFromXMLData,
  createSentenceStructureDataFromSimplifiedAnnotationData,
  sentenceStructureDataToString,
  sentenceStructureDataToXMLString,
  createSentenceElementRange,
  createSentenceStructureRange,
  findRangeById,
  findRangeByStartAndEndWordIndex,
  updateSentenceElementName,
  deleteRange,
  createRelation,
  findRelationById,
  deleteRelation,
  createCoordination,
  findCoordinationById,
  findCoordinationByStartAndEndWordIndex,
  deleteCoordination,
} from "./operations.js";
